version: "3.8"
services:
  cache:
    image: redis:7.0.11
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1
    volumes:
      - /home/cossack/data/redis:/data
  rabbitmq:
    image: rabbitmq:3.11.17-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/home/cossack/data/rabbitmq/log/
      - ~/.docker-conf/rabbitmq/log/:/home/cossack/data/rabbitmq/data/
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge