apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  selector:
    matchLabels:
      app: notification
  replicas: 1
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: bortolini/notification:1.0
          imagePullPolicy: IfNotPresent
          env:
          - name: MAIL_HOST
            value: "mailhog-svc.default.svc.cluster.local"
          - name: MAIL_PORT
            value: "1025"
          - name: RABBITMQ_USER
            value: "guest"
          - name: RABBITMQ_PASSWORD
            value: "guest"
          - name: RABBITMQ_HOST
            value: "rabbitmq-svc.default.svc.cluster.local"
          - name: RABBITMQ_PORT
            value: "5672"
          ports:
            - containerPort: 8082
---   
# apiVersion: v1
# kind: Service
# metadata:
#   name: notification
# spec:
#   selector:
#     app: notification
#   ports:
#     - port: 82
#       targetPort: 8082
#   type: LoadBalancer