apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-2
  labels:
    app: postgres-2
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: psltest
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-2
  labels:
    type: local
    app: postgres-2
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-2  # Sets name of PVC
  labels:
    app: postgres-2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-2  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-2
  template:
    metadata:
      labels:
        app: postgres-2
    spec:
      containers:
        - name: postgres-2
          image: postgres:15.3 # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: postgres-config-2
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb-2
      volumes:
        - name: postgredb-2
          persistentVolumeClaim:
            claimName: postgres-pv-claim-2
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-2 # Sets service name
  labels:
    app: postgres-2 # Labels and Selectors
spec:
  ports:
    - port: 5432 # Sets port to run the postgres application
  selector:
    app: postgres-2
