apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  selector:
    matchLabels:
      app: vote
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: bortolini/vote:1.2
          imagePullPolicy: IfNotPresent
          env:
          - name: POSTGRES_USER
            value: "admin"
          - name: POSTGRES_PASSWORD
            value: "psltest"
          - name: POSTGRES_URL
            value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/postgres"
          - name: RABBITMQ_USER
            value: "guest"
          - name: RABBITMQ_PASSWORD
            value: "guest"
          - name: RABBITMQ_HOST
            value: "rabbitmq-nodeport.default.svc.cluster.local"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: REDIS_HOST
            value: "redis-db-svc.default.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  selector:
    app: vote
  ports:
    - port: 81
      targetPort: 8081
  type: LoadBalancer