apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  selector:
    matchLabels:
      app: vote
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: bortolini/vote:1.6
          imagePullPolicy: IfNotPresent
          env:
          - name: POSTGRES_USER
            value: "<your_user_here>"
          - name: POSTGRES_PASSWORD
            value: "<your_passoword_here>"
          - name: POSTGRES_URL
            value: "<your_database_address_here>"
          - name: RABBITMQ_USER
            value: "guest"
          - name: RABBITMQ_PASSWORD
            value: "guest"
          - name: RABBITMQ_HOST
            value: "rabbitmq-svc.default.svc.cluster.local"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: REDIS_HOST
            value: "redis-db-svc-2.default.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: JDBC_BATCH_SIZE
            value: "250"
          - name: LISTENER_PREFETCH
            value: "250"
          - name: LISTENER_BATCH_SIZE
            value: "250"
          ports:
            - containerPort: 8081
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: vote
# spec:
#   selector:
#     app: vote
#   ports:
#     - port: 81
#       targetPort: 8081
#   type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  selector:
    app: vote
  ports:
    - name: api
      protocol: TCP
      port: 81
      targetPort: 8081